name: update_kumu

# Controls when the workflow will run
on:
  schedule:
    - cron: "00 04 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GSHEET_ACCESS_PASSWORD: ${{ secrets.GSHEET_ACCESS_PASSWORD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: step-1-install-packages & Query dependencies
        run: |
          install.packages('tidyverse')
          install.packages('googlesheets4')
          install.packages('remotes')
          remotes::install_github("jdtrat/tokencodr")
        shell: Rscript {0}
          
      - name: Run-r-script
        run: | 
          Rscript -e "source('scripts/2a_data_for_kumu.R')"
          Rscript -e "source('scripts/2b_data_for_shiny.R')"
       
      - name: Commit RData file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: main
          commit_message: Update Rdata file
          

